import React, { createContext, useState, useContext, useMemo } from 'react';

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  translate: {},
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children, language: initialLanguage = 'en' }) => {
  const [translations, setTranslations] = useState({
    en: {
      language: 'Language', 
      welcom_title: 'Hello', 
      welcom_message: '<b>Welcome to Penny Clicker🎉</b><br /><br />Penny Clicker is a place where you can get rewarded for your web activity in TON, NOT, DOGS, HMSTR, X and other cryptocurrencies. It is also possible to create tasks for other users with different rewards. Join our community and achieve your goals😉', 
      available_tasks: 'Available tasks', 
      no_available_tasks: 'There are no available tasks yet, but they will appear soon. As soon as they appear, we can write to you.',
      connect_notification: 'Connect notification',
      price: 'Reward',
      show: 'View',
      profile: 'Profile',
      about_me: 'A few words about myself...',
      my_tasks: 'My tasks',
      completed_tasks: 'Completed tasks',
      awaiting_check_task: 'Awaiting check task',
      declined_tasks: 'Declined tasks',
      edit_profile: 'Edit profile',
      stop_task_confirmation: 'Are you sure you want to stop the task? The action cannot be undone.',
      unverified_requests: 'You have unverified requests to check for this task. Please check the requests first.',
      add_new_task: 'Add new task',
      active: 'Active',
      moderation: 'Moderation',
      declined: 'Declined',
      archive: 'Archive',
      in_progress_tasks: 'Here you will see the tasks you have created that are in progress.',
      progress: 'Progress',
      balance: 'Balance',
      deadline: 'Deadline',
      edit: 'Edit',
      stop: 'Stop',
      awaiting_check: 'Awaiting check',
      under_moderation_tasks: 'Here you will see the tasks you have created that are being moderation.',
      moderation_failed_tasks: 'Here you will see the tasks you created that did not pass moderation.', 
      completed_or_stopped_tasks: 'Here you will see the tasks you created that were completed or stopped.',
      approved: 'Approved',
      tasks_awaiting_author_check: 'Here you will see tasks that you have completed but have not yet been checked by the author of the task.',
      done: 'Done',
      awaiting_author_check: 'Awaiting author\'s check...',
      rewarded_tasks: 'Here you will see the tasks for which you have already received a reward.',
      task_completed_rewarded: 'Task completed. Reward accrued.',
      declined_by_author: 'Here you will see tasks declined by the author.',
      task_declined: 'Task declined.',
      refill_accepted: 'Refill accepted',
      refill_request_sent: 'The request for refill has been sent. It will be checked soon and the coins will be added to your balance.',
      wallet_copied: 'The wallet address has been copied successfully.',
      wallet_copy_failed: 'Failed to copy address.',
      withdrawal_request_sent: 'Withdrawal request sent',
      withdrawal_request_accepted: 'Withdrawal request accepted. It will be verified soon and the coins will be sent to the specified address.',
      total_balance: 'Total balance',
      deposit: 'Deposit',
      withdrawal: 'Withdrawal',
      transactions_history: 'Transactions history',
      deposit_form: 'Deposit form',
      cryptocurrency: 'Cryptocurrency',
      amount: 'Amount',
      wallet_address: 'Your wallet address',
      next_step: 'Next',
      make_transaction: 'Make a transaction',
      transfer_instruction: 'To complete the balance replenishment, transfer <strong>{sum}</strong> to the address:',
      copy_address: 'Click to copy address', 
      payment_made: 'I made the payment',
      close: 'Close',
      withdrawal_form: 'Withdrawal form',
      task_title: "Task title",
      task_title_placeholder: "Enter title",
      task_description: "Description",
      task_description_placeholder: "Description of how to perform the task and conditions for automatic verification.",
      number_of_executions: "Number of executions",
      total_price: "Total price",
      check_mode: "Check mode",
      manual: "Manual",
      auto: "Auto",
      keyword: "Keyword",
      add_task: "Add task",
      back_to_tasks: "Back to tasks",
      task_added_review: "Task added for review",
      task_added_successfully: "The task has been successfully added and sent for verification. Please wait for a notification.",
      check_list: "Check list",
      awaiting: "Awaiting",
      accepted: "Accepted",
      request_for_verification: "As soon as someone completes the task, their request for verification will be here.",
      accept: "Accept",
      decline: "Decline",
      reward_list: "Here will be a list of those who received a reward for the task.",
      failed_task_list: "Here will be a list of those who failed the task completion check.",
      photo: "Photo",
      nickname: "Nickname",
      nickname_placeholder: "Enter nickname",
      about_me2: "About me",
      about_text: "About text...",
      send_notifications: "Send notifications",
      save: "Save",
      back_to_profile: "Back to profile",
      profile_update: "Profile update",
      data_updated_successfully: "Data updated successfully.",
      edit_task: "Edit task",
      task_changed_review: "Task added for review",
      task_changed_successfully: "The task has been successfully changed and sent for verification. Please wait for a notification.",
      save_changes: "Save",
      execute: "To execution",
      verification_code: "Verification code...",
      check_execution: "Check execution",
      task_complete: "Task complete",
      task_complete_message_author: "Thank you. We have sent a request to check the task to the author. Wait for notification of the verification result.",
      task_complete_message_user: "Thank you. You have successfully completed the task. The reward has been credited."
    },
    uk: {
      language: 'Мова', 
      welcom_title: 'Привіт', 
      welcom_message: '<b>Вітаємо тебе в Penny Clicker🎉</b><br /><br />Penny Clicker — це місце де ти можеш за свою веб-активність отримати винагороду в криптовалюті TON, NOT, DOGS, HMSTR, X та інші. Також є можливість створювати завдання для інших користувачів з різною винагородою. Приєднуйся до нашої спільноти та досягай своїх цілей😉', 
      available_tasks: 'Доступні завдання', 
      no_available_tasks: 'На даний момент немає доступних завдань, але вони з’являться незабаром. Як тільки вони з’являться, ми можемо повідомити вас.',
      connect_notification: 'Підключити сповіщення',
      price: 'Винагорода',
      show: 'Переглянути',
      profile: 'Профіль',
      about_me: 'Кілька слів про себе...',
      my_tasks: 'Мої завдання',
      completed_tasks: 'Виконані завдання',
      awaiting_check_task: 'Завдання на перевірці',
      declined_tasks: 'Відхилені завдання',
      edit_profile: 'Редагувати профіль',
      stop_task_confirmation: 'Ви впевнені, що хочете зупинити завдання? Цю дію не можна скасувати.',
      unverified_requests: 'У вас є неперевірені запити на це завдання. Будь ласка, перевірте їх спочатку.',
      add_new_task: 'Додати нове завдання',
      active: 'Активні',
      moderation: 'На модерації',
      declined: 'Відхилено',
      archive: 'Архів',
      in_progress_tasks: 'Тут будуть показані ваші завдання, які виконуються.',
      progress: 'Прогрес',
      balance: 'Баланс',
      deadline: 'Кінцевий термін',
      edit: 'Змінити',
      stop: 'Зупинити',
      awaiting_check: 'На перевірці',
      under_moderation_tasks: 'Тут будуть показані завдання, які знаходяться на модерації.',
      moderation_failed_tasks: 'Тут ви побачите створені вами завдання, які не пройшли модерацію.', 
      completed_or_stopped_tasks: 'Тут будуть завершені або зупинені завдання.',
      approved: 'Схвалено',
      tasks_awaiting_author_check: 'Тут будуть завдання, які ви виконали, але ще не перевірені автором.',
      done: 'Виконано',
      awaiting_author_check: 'Очікує перевірки автором...',
      rewarded_tasks: 'Тут будуть завдання, за які ви вже отримали винагороду.',
      task_completed_rewarded: 'Завдання виконано. Винагорода нарахована.',
      declined_by_author: 'Тут будуть завдання, відхилені автором.',
      task_declined: 'Завдання відхилено.',
      refill_accepted: 'Поповнення підтверджено',
      refill_request_sent: 'Запит на поповнення відправлено. Він буде перевірений найближчим часом, і монети буде додано на ваш баланс.',
      wallet_copied: 'Адреса гаманця успішно скопійовано.',
      wallet_copy_failed: 'Не вдалося скопіювати адресу.',
      withdrawal_request_sent: 'Запит на виведення відправлено',
      withdrawal_request_accepted: 'Запит на виведення підтверджено. Монети буде відправлено найближчим часом.',
      total_balance: 'Загальний баланс',
      deposit: 'Поповнити',
      withdrawal: 'Виведення',
      transactions_history: 'Історія транзакцій',
      deposit_form: 'Форма поповнення',
      cryptocurrency: 'Криптовалюта',
      amount: 'Сума',
      wallet_address: 'Адреса вашого гаманця',
      next_step: 'Далі',
      make_transaction: 'Зробити транзакцію',
      transfer_instruction: 'Для поповнення балансу переведіть <strong>{sum}</strong> на адресу:',
      copy_address: 'Натисніть, щоб скопіювати адресу', 
      payment_made: 'Я виконав платіж',
      close: 'Закрити',
      withdrawal_form: 'Форма виведення',
      task_title: "Назва завдання",
      task_title_placeholder: "Введіть назву",
      task_description: "Опис",
      task_description_placeholder: "Опис, як виконати завдання, та умови автоматичної перевірки.",
      number_of_executions: "Кількість виконань",
      total_price: "Загальна ціна",
      check_mode: "Режим перевірки",
      manual: "Ручний",
      auto: "Автоматичний",
      keyword: "Ключове слово",
      add_task: "Додати завдання",
      back_to_tasks: "Назад до завдань",
      task_added_review: "Завдання додано на перевірку",
      task_added_successfully: "Завдання успішно додано та надіслано на перевірку. Очікуйте, ви отримаєте повідмлення.",
      check_list: "Список перевірки",
      awaiting: "Очікування",
      accepted: "Прийнято",
      request_for_verification: "Як тільки хтось виконає завдання, його запит на перевірку буде тут.",
      accept: "Прийняти",
      decline: "Відхилити",
      reward_list: "Тут буде список тих, хто отримав винагороду за завдання.",
      failed_task_list: "Тут буде список тих, хто не пройшов перевірку виконання завдання.",
      photo: "Фото",
      nickname: "Псевдонім",
      nickname_placeholder: "Введіть псевдонім",
      about_me2: "Про мене",
      about_text: "Текст про себе...",
      send_notifications: "Надсилати сповіщення",
      save: "Зберегти",
      back_to_profile: "Назад до профілю",
      profile_update: "Оновлення профілю",
      data_updated_successfully: "Дані успішно оновлено.",
      edit_task: "Редагувати завдання",
      task_changed_review: "Завдання додано на перевірку",
      task_changed_successfully: "Завдання успішно змінено та надіслано на перевірку. Очікуйте, ви отримаєте повідмлення.",
      save_changes: "Зберегти",
      execute: "Виконати",
      verification_code: "Код перевірки...",
      check_execution: "Перевірка виконання",
      task_complete: "Завдання виконано",
      task_complete_message_author: "Дякуємо. Ми надіслали запит на перевірку завдання автору. Очікуйте повідомлення про результат перевірки.",
      task_complete_message_user: "Дякуємо. Ви успішно виконали завдання. Винагороду зараховано."
    },
    es: {
      language: 'Idioma', 
      welcom_title: 'Saludos', 
      welcom_message: '<b>Bienvenido a Penny Clicker🎉</b><br /><br />Penny Clicker es un lugar donde puedes recibir recompensas por tu actividad web en las criptomonedas TON, NOT, DOGS, HMSTR, X y otras. También es posible crear tareas para otros usuarios con diferentes recompensas. Únete a nuestra comunidad y logra tus objetivos😉', 
      available_tasks: 'Tareas disponibles', 
      no_available_tasks: 'Aún no hay tareas disponibles, pero aparecerán pronto. Tan pronto como aparezcan, podemos escribirle.',
      connect_notification: 'Conectar notificación',
      price: 'Remuneración',
      show: 'Revisar',
      profile: 'Perfil',
      about_me: 'Unas palabras sobre mí...',
      my_tasks: 'Mis tareas',
      completed_tasks: 'Tareas completadas',
      awaiting_check_task: 'Tarea pendiente de revisión',
      declined_tasks: 'Tareas rechazadas',
      edit_profile: 'Editar perfil',
      stop_task_confirmation: '¿Está seguro de que desea detener la tarea? Esta acción no se puede deshacer.',
      unverified_requests: 'Tiene solicitudes sin verificar para esta tarea. Por favor, verifíquelas primero.',
      add_new_task: 'Agregar nueva tarea',
      active: 'Activa',
      moderation: 'Moderación',
      declined: 'Rechazada',
      archive: 'Archivo',
      in_progress_tasks: 'Aquí verá las tareas que ha creado y que están en progreso.',
      progress: 'Progreso',
      balance: 'Saldo',
      deadline: 'Fecha límite',
      edit: 'Editar',
      stop: 'Detener',
      awaiting_check: 'En revisión',
      under_moderation_tasks: 'Aquí verá las tareas que ha creado y que están siendo moderadas.',
      moderation_failed_tasks: 'Aquí verás las tareas que creaste y que no pasaron la moderación.', 
      completed_or_stopped_tasks: 'Aquí verá las tareas que ha creado y que se completaron o detuvieron.',
      approved: 'Aprobadas',
      tasks_awaiting_author_check: 'Aquí verá las tareas que ha completado pero que aún no han sido verificadas por el autor.',
      done: 'Hecho',
      awaiting_author_check: 'Esperando la verificación del autor...',
      rewarded_tasks: 'Aquí verá las tareas por las que ya ha recibido una recompensa.',
      task_completed_rewarded: 'Tarea completada. Recompensa acreditada.',
      declined_by_author: 'Aquí verá las tareas rechazadas por el autor.',
      task_declined: 'Tarea rechazada.',
      refill_accepted: 'Recarga aceptada',
      refill_request_sent: 'La solicitud de recarga se ha enviado. Será verificada pronto y las monedas se añadirán a su saldo.',
      wallet_copied: 'La dirección de la billetera se ha copiado con éxito.',
      wallet_copy_failed: 'Error al copiar la dirección.',
      withdrawal_request_sent: 'Solicitud de retiro enviada',
      withdrawal_request_accepted: 'Solicitud de retiro aceptada. Será verificada pronto y las monedas se enviarán a la dirección especificada.',
      total_balance: 'Saldo total',
      deposit: 'Depósito',
      withdrawal: 'Retiro',
      transactions_history: 'Historial de transacciones',
      deposit_form: 'Formulario de depósito',
      cryptocurrency: 'Criptomoneda',
      amount: 'Cantidad',
      wallet_address: 'Su dirección de billetera',
      next_step: 'Próximo',
      make_transaction: 'Hacer una transacción',
      transfer_instruction: 'Para completar la recarga del saldo, transfiera <strong>{sum}</strong> a la dirección:',
      copy_address: 'Haga clic para copiar la dirección', 
      payment_made: 'He realizado el pago',
      close: 'Cerrar',
      withdrawal_form: 'Formulario de retiro',
      task_title: "Título de la tarea",
      task_title_placeholder: "Ingresar título",
      task_description: "Descripción",
      task_description_placeholder: "Descripción de cómo realizar la tarea y las condiciones para la verificación automática.",
      number_of_executions: "Número de ejecuciones",
      total_price: "Precio total",
      check_mode: "Modo de verificación",
      manual: "Manual",
      auto: "Automático",
      keyword: "Palabra clave",
      add_task: "Agregar tarea",
      back_to_tasks: "Volver a las tareas",
      task_added_review: "Tarea añadida para revisión",
      task_added_successfully: "La tarea se agregó y envió exitosamente para su revisión. Espera, recibirás un mensaje.",
      check_list: "Lista de verificación",
      awaiting: "En espera",
      accepted: "Aceptada",
      request_for_verification: "Tan pronto como alguien complete la tarea, su solicitud de verificación estará aquí.",
      accept: "Aceptar",
      decline: "Rechazar",
      reward_list: "Aquí habrá una lista de quienes recibieron una recompensa por la tarea.",
      failed_task_list: "Aquí habrá una lista de quienes no superaron la verificación de finalización de la tarea.",
      photo: "Foto",
      nickname: "Apodo",
      nickname_placeholder: "Ingresar apodo",
      about_me2: "Acerca de mí",
      about_text: "Texto sobre mí...",
      send_notifications: "Enviar notificaciones",
      save: "Guardar",
      back_to_profile: "Volver al perfil",
      profile_update: "Actualización del perfil",
      data_updated_successfully: "Datos actualizados con éxito.",
      edit_task: "Editar tarea",
      task_changed_review: "Tarea añadida para revisión",
      task_changed_successfully: "La tarea se ha modificado correctamente y se ha enviado para su revisión. Espera, recibirás un mensaje.",
      save_changes: "Guardar cambios",
      execute: "Ejecutar",
      verification_code: "Código de verificación...",
      check_execution: "Verificar ejecución",
      task_complete: "Tarea completada",
      task_complete_message_author: "Gracias. Hemos enviado una solicitud al autor para verificar la tarea. Espere la notificación del resultado de la verificación.",
      task_complete_message_user: "Gracias. Has completado la tarea con éxito. La recompensa ha sido acreditada."
    },
    ru: {
      language: 'Язык', 
      welcom_title: 'Привет', 
      welcom_message: '<b>Приветствуем тебя в Penny Clicker🎉</b><br /><br />Penny Clicker — это место, где ты можешь за свою web-активность получить вознаграждение в криптовалюте TON, NOT, DOGS, HMSTR, X и другие. Также есть возможность создавать задания для других пользователей с разным вознаграждением. Присоединяйся к нашему сообществу и достигай своих целей😉', 
      available_tasks: 'Доступные задания', 
      no_available_tasks: 'Пока нет доступных задач, но они скоро появятся. Как только они появятся, мы можем написать вам.',
      connect_notification: 'Подключить уведомление',
      price: 'Вознаграждение',
      show: 'Просмотреть',
      profile: 'Профиль',
      about_me: 'Несколько слов о себе...',
      my_tasks: 'Мои задачи',
      completed_tasks: 'Выполненные задачи',
      awaiting_check_task: 'Задача на проверке',
      declined_tasks: 'Отклоненные задачи',
      edit_profile: 'Редактировать профиль',
      stop_task_confirmation: 'Вы уверены, что хотите остановить задачу? Это действие нельзя отменить.',
      unverified_requests: 'У вас есть непроверенные запросы по этой задаче. Пожалуйста, проверьте их сначала.',
      add_new_task: 'Добавить новую задачу',
      active: 'Активные',
      moderation: 'На модерации',
      declined: 'Отклонено',
      archive: 'Архив',
      in_progress_tasks: 'Здесь будут отображаться созданные вами задачи, которые находятся в процессе выполнения.',
      progress: 'Прогресс',
      balance: 'Баланс',
      deadline: 'Срок выполнения',
      edit: 'Изменить',
      stop: 'Остановить',
      awaiting_check: 'На проверке',
      under_moderation_tasks: 'Здесь будут задачи, созданные вами и находящиеся на модерации.',
      moderation_failed_tasks: 'Здесь вы увидите созданные вами задания, которые не прошли модерацию.', 
      completed_or_stopped_tasks: 'Здесь будут завершенные или остановленные вами задачи.',
      approved: 'Одобрено',
      tasks_awaiting_author_check: 'Здесь будут задачи, выполненные вами, но еще не проверенные автором.',
      done: 'Выполнено',
      awaiting_author_check: 'Ожидает проверки автором...',
      rewarded_tasks: 'Здесь будут задачи, за которые вы уже получили вознаграждение.',
      task_completed_rewarded: 'Задача выполнена. Вознаграждение начислено.',
      declined_by_author: 'Здесь будут задачи, отклоненные автором.',
      task_declined: 'Задача отклонена.',
      refill_accepted: 'Пополнение принято',
      refill_request_sent: 'Запрос на пополнение отправлен. Он будет проверен в ближайшее время, и монеты будут добавлены на ваш баланс.',
      wallet_copied: 'Адрес кошелька успешно скопирован.',
      wallet_copy_failed: 'Не удалось скопировать адрес.',
      withdrawal_request_sent: 'Запрос на вывод отправлен',
      withdrawal_request_accepted: 'Запрос на вывод принят. Он будет проверен в ближайшее время, и монеты будут отправлены на указанный адрес.',
      total_balance: 'Общий баланс',
      deposit: 'Пополнить',
      withdrawal: 'Вывести',
      transactions_history: 'История транзакций',
      deposit_form: 'Форма пополнения',
      cryptocurrency: 'Криптовалюта',
      amount: 'Сумма',
      wallet_address: 'Ваш адрес кошелька',
      next_step: 'Далее',
      make_transaction: 'Совершить транзакцию',
      transfer_instruction: 'Для завершения пополнения баланса переведите <strong>{sum}</strong> на адрес:',
      copy_address: 'Нажмите, чтобы скопировать адрес', 
      payment_made: 'Я совершил платеж',
      close: 'Закрыть',
      withdrawal_form: 'Форма вывода',
      task_title: "Название задания",
      task_title_placeholder: "Введите название",
      task_description: "Описание",
      task_description_placeholder: "Описание того, как выполнить задание, и условия автоматической проверки.",
      number_of_executions: "Количество выполнений",
      total_price: "Общая стоимость",
      check_mode: "Режим проверки",
      manual: "Ручной",
      auto: "Автоматический",
      keyword: "Ключевое слово",
      add_task: "Добавить задание",
      back_to_tasks: "Назад к заданиям",
      task_added_review: "Задание добавлено на проверку",
      task_added_successfully: "Задание успешно добавлено и отправлено на проверку. Ожидайте, что вы получите сообщение.",
      check_list: "Список проверок",
      awaiting: "В ожидании",
      accepted: "Принято",
      request_for_verification: "Как только кто-то выполнит задание, его запрос на проверку будет здесь.",
      accept: "Принять",
      decline: "Отклонить",
      reward_list: "Здесь будет список тех, кто получил награду за задание.",
      failed_task_list: "Здесь будет список тех, кто не прошел проверку выполнения задания.",
      photo: "Фото",
      nickname: "Никнейм",
      nickname_placeholder: "Введите никнейм",
      about_me2: "О себе",
      about_text: "Текст о себе...",
      send_notifications: "Отправлять уведомления",
      save: "Сохранить",
      back_to_profile: "Назад к профилю",
      profile_update: "Обновление профиля",
      data_updated_successfully: "Данные успешно обновлены.",
      edit_task: "Редактировать задание",
      task_changed_review: "Задание добавлено на проверку",
      task_changed_successfully: "Задание успешно изменено и отправлено на проверку. Вы всегда можете увидеть статус проверки (активное/отклонено) в списке ваших заданий.",
      save_changes: "Сохранить изменения",
      execute: "Выполнить",
      verification_code: "Код проверки...",
      check_execution: "Проверка выполнения",
      task_complete: "Задание выполнено",
      task_complete_message_author: "Спасибо. Мы отправили запрос автору для проверки задания. Ожидайте уведомления о результате проверки.",
      task_complete_message_user: "Спасибо. Вы успешно выполнили задание. Награда начислена."
    }
  });

  // Current language
  const [language, setLanguage] = useState(initialLanguage);

  // Memoize the translation object for the current language
  const translate = useMemo(() => translations[language] || {}, [language, translations]);

  return (
    <LanguageContext.Provider value={{ setTranslations, language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};